---
- name: Fresh system configuration
  hosts: localhost
  tasks:
    - name: Ansible user
      user: name=ansible comment="Ansible User" shell=/bin/bash

    - name: Set up authorized_keys for the ansible user
      authorized_key: user=ansible key={{ item }}
      with_file:
        - public_keys/test1.pub

    - name: Install packages
      apt: name={{ item }} state=present
      with_items:
        - openssh-server
        - sudo
