---
- name: Fresh system configuration
  hosts: localhost
  tasks:
    - name: Ansible user
      user: name=ansible comment="Ansible User"

    - name: Set up authorized_keys for the ansible user
      authorized_key: user=ansible key="{{ item }}"
      with_file:
        - public_keys/test1.pub

    - name: Install ssh
      apt: name=openssh-server state=present
